### PR TITLE
Cascadia2020

### PR DESCRIPTION
**Pull request by datalorax**
Updates the site for 2020. Not everything we need is in there yet, but I think this gets us enough that we can at least get the site live and announce the conference. It has all the speakers in it and a link for people to register.

### CODE REVIEW

**Comment by sckott** [comment]
on the landing page you have 

> We feature a single track of 15-minutes talks, ranging from beginner to advanced applications of R.

but the agenda https://deploy-preview-41--brave-albattani-75ca02.netlify.com/agenda/ has only lightning talks that I can see

**Comment by sckott** [comment]
not a big deal but theres pagination on the speakers page thats probably not needed

Screen Shot 2020-02-18 at 10 14 02 AM

**Review by sckott — COMMENTED** [review]
made a few comments, otherwise looks good

**Comment by datalorax** [comment]
I couldn't quickly figure out how to remove the pagination so I skipped that one, but I did update the talks part and I updated the sponsors on the landing page. Let's get it out there! 🎉

**Comment by thebioengineer** [comment]
Would it be possible to preserve last years pages so people that want to reference them can? The Eventbank site is not great and I think will be going away since we didnt give them more money.

**Pull request merged**
