### PR TITLE
tweak menubar height

### PR DESCRIPTION
**Pull request by laderast**

### CODE REVIEW

**Comment by laderast** [comment]
The logo overlaps now with the menubar, but at least it's visible

**Comment by sckott** [comment]
thanks @laderast !

but it seems to be overlapping the header title now, for each page

original 

screen shot 2018-04-05 at 4 18 53 pm

vs. 

this PR 

screen shot 2018-04-05 at 4 18 49 pm

**Comment by laderast** [comment]
It's weird - because when I run my local hugo, the problem is fixed when I resized `logo2.png`, `logo2-small.png` and `favico.ico` - but not on the netlify version.

**Comment by laderast** [comment]
screen shot 2018-04-05 at 4 37 24 pm

**Comment by sckott** [comment]
sorry, there's two static files, one at the top level and one within the theme folder itself - the original them folder had both of those, so I kept those, 

however, I don't think the overlap thing above i reported has to do with the sticker image size, but rather the change you made in the padding

**Comment by laderast** [comment]
Ah, yes, the padding settings are super confusing. Let's not worry about it for now - you can close this PR

**Comment by sckott** [comment]
ok, well, maybe we can leave it open as a reminder to fix it when we get around to it

**Pull request closed without merging**
