### PR TITLE
Updating website with 2019 information

### PR DESCRIPTION
**Pull request by thebioengineer**
updating website and adding speaker information

### CODE REVIEW

**Comment by sckott** [comment]
@thebioengineer  here's the preview https://deploy-preview-34--brave-albattani-75ca02.netlify.com/ in case you didn't see it yet

**Comment by thebioengineer** [comment]
Thanks @sckott, I've been reviewing my changes as I go 👍 

I'll post here once I think it is ready for prime time

**Comment by sckott** [comment]
- would be good to link to speakers page from the agenda page 
- on the coc page, add one or two pople that will be the contact person during the event for coc violations

- somehow some text and icon colors got changed only on the agenda page

Screen Shot 2019-05-03 at 6 33 02 PM

- the content on the agenda page seems to not be responsive. so it doesn't look good on mobile. on mobile, compare your agenda page to the agenda page for 2018 - i haven't taken time to identify what it is yet, but it would be best to fix since many people will probably be looking at this on their phone, esp. at the event

**Comment by thebioengineer** [comment]
@sckott I believe I have address all of your concerns above. Let me know if anything else needs changing!

**Comment by sckott** [comment]
okay, looks good

**Pull request merged**
